language: cpp
before_install:
#  - sudo add-apt-repository ppa:csaba-kertesz/random -y
#  - sudo apt-get update -q
#  - sudo apt-get install cmake -y
install:
  - apt-cache show cmake
  - apt-cache search soci
script:
  - mkdir build && cd build && cmake -Dtest=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
