language: cpp
before_install:
  - sudo add-apt-repository ppa:wacha/soci
  - sudo apt-get update -q
  - curl https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
install:
  - apt-cache show cmake
  - apt-cache search soci
script:
  - mkdir build && cd build && cmake -Dtest=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
